name: RadioDroid Instrumented Tests CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  integration-test:
    runs-on: macOS-10.15
    strategy:
      matrix:
        api: [21, 27, 29]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: malinskiy/action-android/install-sdk@release/0.1.3
      - name: Instrumented tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.3
        timeout-minutes: 35
        with:
          cmd: ./gradlew connectedFreeDebugAndroidTest
          api: ${{ matrix.api }}
          tag: default
          abi: x86
          disableAnimations: true
          hardwareProfile: Nexus 6
      - name: Save instrumented tests output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: instrumented-tests-result
          path: build/reports/tests/instrumentedTests
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log
